% Ex 6-3.29: the volume of the solid generated by revolving the region
%   x^(3/4) + y^(3/4) = 1, y = 0, x = 0
% about the y-axis.

f = @(x) (1-x.^(4/3)).^(3/4);

x = 0:0.01:1;

px = [0 x];
py = [0 f(x)];

fill(px, py, [0.9, 0.9, 0.95], 'linestyle', ':')
grid on
xlim([-0.25 1.5])
ylim([-0.25 1.5])
g = @(x) x .* f(x);

fprintf('V = %.4f\n', 2*pi*quad(g, 0, 1))

